# Generated by Django 5.2 on 2025-04-30 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=50, unique=True, verbose_name='Категория льгот')),
                ('percentage', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Процент скидки')),
            ],
        ),
    ]
