# Generated by Django 5.2 on 2025-04-30 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_customuser_patient'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='patient',
        ),
        migrations.AddField(
            model_name='customuser',
            name='birth_year',
            field=models.IntegerField(blank=True, null=True, verbose_name='Год рождения'),
        ),
    ]
