# Generated by Django 5.2 on 2025-04-30 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_customuser_patient_customuser_birth_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='birth_year',
            field=models.IntegerField(default=1, verbose_name='Год рождения'),
            preserve_default=False,
        ),
    ]
