# Generated by Django 5.2 on 2025-04-30 12:05

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0003_patient_created_at_patient_created_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Дата создания'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='service',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='service',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата обновления'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='discount_category',
            field=models.CharField(choices=[('none', 'Без льгот'), ('pensioner', 'Пенсионер'), ('disabled', 'Инвалид'), ('veteran', 'Ветеран')], default='none', max_length=20, verbose_name='Категория льгот'),
        ),
        migrations.AlterField(
            model_name='service',
            name='name',
            field=models.CharField(max_length=200, unique=True, verbose_name='Название услуги'),
        ),
    ]
