# Generated by Django 5.2 on 2025-04-30 12:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0005_alter_patient_created_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visit',
            name='created_by',
        ),
        migrations.AlterField(
            model_name='visit',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinic.doctor'),
        ),
        migrations.AlterField(
            model_name='visit',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinic.patient'),
        ),
        migrations.AlterField(
            model_name='visit',
            name='services',
            field=models.ManyToManyField(through='clinic.VisitService', to='clinic.service'),
        ),
        migrations.AlterField(
            model_name='visit',
            name='total_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Итоговая стоимость'),
        ),
    ]
