# Generated by Django 5.2 on 2025-04-30 13:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0008_alter_visit_created_by_alter_visit_patient_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visit',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinic.doctor', verbose_name='Врач'),
        ),
        migrations.AlterField(
            model_name='visit',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinic.patient', verbose_name='Пациент'),
        ),
        migrations.AlterField(
            model_name='visit',
            name='services',
            field=models.ManyToManyField(through='clinic.VisitService', to='clinic.service', verbose_name='Услуги'),
        ),
        migrations.AlterField(
            model_name='visitservice',
            name='quantity',
            field=models.PositiveIntegerField(default=1, verbose_name='Количество'),
        ),
    ]
