# Generated by Django 5.2 on 2025-04-30 13:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0011_patient_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='middle_name',
        ),
        migrations.AlterField(
            model_name='patient',
            name='birth_year',
            field=models.IntegerField(verbose_name='Год рождения'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='discount_category',
            field=models.CharField(choices=[('none', 'Нет'), ('pensioner', 'Пенсионер'), ('disabled', 'Инвалид')], default='none', max_length=50, verbose_name='Льготная категория'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='visit',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='visit',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinic.doctor'),
        ),
        migrations.AlterField(
            model_name='visit',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinic.patient'),
        ),
        migrations.AlterField(
            model_name='visit',
            name='services',
            field=models.ManyToManyField(through='clinic.VisitService', to='clinic.service'),
        ),
        migrations.AlterField(
            model_name='visitservice',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
