# Generated by Django 5.2 on 2025-04-30 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0012_remove_patient_created_at_remove_patient_created_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='discount_category',
        ),
        migrations.AlterField(
            model_name='visit',
            name='total_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Стоимость'),
        ),
    ]
